
[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "~1.3.1"

[[constraint]]
  name = "github.com/Masterminds/sprig"
  version = "2.14.1"

[[constraint]]
  name = "github.com/Masterminds/vcs"
  version = "~1.11.0"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "4.0.0"

[[constraint]]
  name = "github.com/gobwas/glob"
  version = "0.2.1"

[[constraint]]
  name = "github.com/gosuri/uitable"
  branch = "master"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.13"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.13"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.13"

[[override]]
  name = "k8s.io/apiserver"
  branch = "release-1.13"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.13"

[[override]]
  name = "github.com/imdario/mergo"
  version = "v0.3.5"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.3.0"

[prune]
  go-tests = true
  unused-packages = true

