[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "~0.3.1"

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "~1.4.2"

[[constraint]]
  name = "github.com/Masterminds/sprig"
  version = "^2.20.0"

[[constraint]]
  name = "github.com/Masterminds/vcs"
  version = "~1.13.0"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "9.0.0"

[[constraint]]
  name = "github.com/gobwas/glob"
  version = "~0.2.3"

[[constraint]]
  name = "github.com/gosuri/uitable"
  branch = "master"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.15"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.15"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.15.1"

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.15"

[[constraint]]
  name = "github.com/deislabs/oras"
  version = "0.5.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.3.0"

[[constraint]]
  name = "github.com/docker/go-units"
  version = "~0.3.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.3.0"

[[override]]
  name = "sigs.k8s.io/kustomize"
  version = "2.0.3"

[[override]]
  name = "k8s.io/apiserver"
  branch = "release-1.15"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.15"

[[override]]
  name = "github.com/imdario/mergo"
  version = "v0.3.5"

# This override below necessary for using docker/distribution as a test dependency
[[override]]
  name = "rsc.io/letsencrypt"
  branch = "master"
  source = "https://github.com/dmcgowan/letsencrypt.git"

# gopkg.in is broken
#
#   https://github.com/golang/dep/issues/1760

[[override]]
  name = "gopkg.in/inf.v0"
  source = "https://github.com/go-inf/inf.git"

[[override]]
  name = "gopkg.in/square/go-jose.v1"
  version = "~1.1.2"
  source = "https://github.com/square/go-jose.git"

[[override]]
  name = "gopkg.in/square/go-jose.v2"
  version = "~2.3.0"
  source = "https://github.com/square/go-jose.git"

[[override]]
  name = "gopkg.in/yaml.v2"
  source = "https://github.com/go-yaml/yaml"

[prune]
  go-tests = true

[[constraint]]
  name = "github.com/xeipuuv/gojsonschema"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.4"

[[constraint]]
  name = "sigs.k8s.io/yaml"
  version = "1.1.0"
