version: 2
jobs:
  build:
    working_directory: /go/src/k8s.io/helm
    parallelism: 3
    docker:
      - image: golang:1.14
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    environment:
      PROJECT_NAME: "kubernetes-helm"
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - restore_cache:
          keys:
            - glide-2-{{ checksum "glide.yaml" }}-{{ checksum "glide.lock" }}
            - glide-2- # used as a fall through if the checksum fails to find exact entry
      - run:
          name: install dependencies
          command: .circleci/bootstrap.sh
      - save_cache:
          key: glide-2-{{ checksum "glide.yaml" }}-{{ checksum "glide.lock" }}
          paths:
            - /root/.glide  # Where the glide cache is stored
      - run:
          name: test
          command: .circleci/test.sh
      - deploy:
          name: deploy
          command: .circleci/deploy.sh
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
