version: 2
jobs:
  build:
    working_directory: /go/src/k8s.io/helm
    parallelism: 3
    docker:
      - image: golang:1.8
    environment:
      PROJECT_NAME: "kubernetes-helm"
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - glide-{{ checksum "glide.yaml" }}-{{ checksum "glide.lock" }}
            - glide- # used as a fall through if the checksum fails to find exact entry
      - run:
          name: install dependencies
          command: .circleci/bootstrap.sh
      - save_cache:
          key: glide-{{ checksum "glide.yaml" }}-{{ checksum "glide.lock" }}
          paths:
            - /root/.glide  # Where the glide cache is stored
      - run:
          name: test
          command: .circleci/test.sh
      - deploy:
          name: deploy
          command: .circleci/deploy.sh
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
