name: release
on:
  create:
    tags:
      - v*
  push:
    branches:
      - main

# Note the only differences between release and canary-release jobs are:
# - only canary passes --overwrite flag
# - the VERSION make variable passed to 'make dist checksum' is expected to
#   be "canary" if the job is triggered by a push to "main" branch. If the
#   job is triggered by a tag push, VERSION should be the tag ref.
jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # pin@v3.6.0
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # pin@4.1.0
        with:
          go-version: '1.20'
      
      - name: Run unit tests
        run: make test-coverage

      - name: Build Helm Binaries
        run: |
          make build-cross
          make dist checksum VERSION="${{ github.ref_name }}"
      
      - name: Set latest version
        run: |
          # Push the latest semver tag, excluding prerelease tags
          git tag | sort -r --version-sort | grep '^v[0-9]' | grep -v '-' | head -n1 > _dist/helm-latest-version

      - name: Upload Binaries
        uses: bacongobbler/azure-blob-storage-upload@50f7d898b7697e864130ea04c303ca38b5751c50 # pin@3.0.0
        env:
          AZURE_STORAGE_CONNECTION_STRING: "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
          AZURE_STORAGE_CONTAINER_NAME: "${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}"
        with:
          source_dir: _dist
          container_name: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          extra_args: '--pattern helm-*'

      - name: Login to Docker Hub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # pin@3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker images
        uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8 # pin@5.0.0
        with:
          args: release --clean

  canary-release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout source code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # pin@v3.6.0

      - name: Setup Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # pin@4.1.0
        with:
          go-version: '1.20'

      - name: Run unit tests
        run: make test-coverage

      - name: Build Helm Binaries
        run: |
          make build-cross
          make dist checksum VERSION="canary"

      - name: Upload Binaries
        uses: bacongobbler/azure-blob-storage-upload@50f7d898b7697e864130ea04c303ca38b5751c50 # pin@3.0.0
        with:
          source_dir: _dist
          container_name: ${{ secrets.AZURE_STORAGE_CONTAINER_NAME }}
          connection_string: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
          extra_args: '--pattern helm-*'
          # WARNING: this will overwrite existing blobs in your blob storage
          overwrite: 'true'
