name: Lint Bash Scripts

on:
  pull_request:
    paths:
      - 'scripts/**.sh'
  push:
    branches:
      - main
    paths:
      - 'scripts/**.sh'

permissions:
  contents: read

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # pin@v6.0.1
        with:
          persist-credentials: false

      - name: Run ShellCheck
        run: shellcheck ./scripts/**/*.sh
